name: Melodic Ubuntu 18.04

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - uses: betwo/github-setup-catkin@v1.1.1
      with:
        ros-version: 'melodic'
        workspace: '$GITHUB_WORKSPACE'
    - run: catkin_make_isolated